// https://pws.yarb00.dev

using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Reflection;
using System.Runtime.InteropServices;
using System.Windows.Forms;

namespace PWSandbox;

internal static class Program
{
	public const string Website = "https://pws.yarb00.dev";
	public const string License = """
		Copyright (c) 2024-2026 yarb00

		Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:

		The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

		THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
		""";

	public static readonly Version Version = Assembly.GetExecutingAssembly().GetName().Version ?? throw new UnreachableException("Assembly version can't be null.");
	public static readonly string FriendlyVersion = Version.ToString(3);

	[STAThread]
	public static void Main(string[] args)
	{
		if (!Debugger.IsAttached)
		{
			Application.SetUnhandledExceptionMode(UnhandledExceptionMode.CatchException);
			Application.ThreadException += static (_, e) => HandleUnhandledException(e.Exception, true);
			AppDomain.CurrentDomain.UnhandledException += static (_, e) => HandleUnhandledException((Exception)e.ExceptionObject);
		}

		ApplicationConfiguration.Initialize();
		Application.SetColorMode(SystemColorMode.System);

		if (args.Length == 0) Application.Run(new MenuForm());
		else Application.Run(new ArgumentsApplicationContext(args));
	}

	private static void HandleUnhandledException(Exception e, bool isResumingAllowed = false)
	{
		string
			issueTitle = $"Unhandled exception: `{e.GetType().Name}`",
			issueBody = $"""
				***Auto-generated by PWSandbox.***

				## Environment

				**PWSandbox version**: `{FriendlyVersion}`

				**OS**: `{RuntimeInformation.OSDescription}`

				## Exception details

				```
				{e}
				```
				""",
			issueReportLink = $"{Website}/issue/report/client?title={Uri.EscapeDataString(issueTitle)}&body={Uri.EscapeDataString(issueBody)}",
			issueReportLinkStart = $"<a href=\"{issueReportLink}\">",
			issueReportLinkEnd = "</a>",
			resumingNotAllowedText = Localization.StringById[StringId.UnhandledExceptionResumingNotAllowedText]
				.Replace("\\(REPORT_LINK_START)", issueReportLinkStart).Replace("\\(REPORT_LINK_END)", issueReportLinkEnd),
			resumingAllowedText = Localization.StringById[StringId.UnhandledExceptionResumingAllowedText]
				.Replace("\\(REPORT_LINK_START)", issueReportLinkStart).Replace("\\(REPORT_LINK_END)", issueReportLinkEnd);

		TaskDialogButtonCollection buttons = [TaskDialogButton.Close];
		if (isResumingAllowed) buttons.Add(TaskDialogButton.Continue);

		TaskDialogPage unhandledExceptionDialog = new()
		{
			Caption = Localization.StringById[StringId.UnhandledExceptionTitle],
			Heading = "x_x",
			Icon = TaskDialogIcon.ShieldErrorRedBar,

			RightToLeftLayout = Localization.AreStringsRightToLeft,
			SizeToContent = true,
			EnableLinks = true,

			Buttons = buttons,

			Expander = new TaskDialogExpander
			{
				CollapsedButtonText = Localization.StringById[StringId.ShowDetailsAction],
				ExpandedButtonText = Localization.StringById[StringId.HideDetailsAction],
				Text = $"""
					{Localization.StringById[StringId.DetailsSection]}
					{e}
					"""
			},

			Text = isResumingAllowed ? resumingAllowedText : resumingNotAllowedText
		};

		unhandledExceptionDialog.LinkClicked += (_, e) => Process.Start(new ProcessStartInfo(e.LinkHref) { UseShellExecute = true });

		TaskDialogButton result = TaskDialog.ShowDialog(unhandledExceptionDialog);
		if (result == TaskDialogButton.Close) Environment.FailFast("An unhandled exception occurred.", e);
	}

	private class ArgumentsApplicationContext : ApplicationContext
	{
		private int openForms = 0;

		public ArgumentsApplicationContext(string[] filePaths)
		{
			int totalMaps = filePaths.Length, successfulMaps = 0, failedMaps = 0;
			List<string> results = [];

			foreach (string filePath in filePaths)
			{
				Map map;
				try
				{
					map = MapParser.ParseMapFromFile(filePath);
				}
				catch (Exception ex)
				{
					failedMaps++;
					results.Add(
						Localization.StringById[StringId.MapLoadingFailedText]
						.Replace("\\(MAP)", filePath).Replace("\\(ERROR_MESSAGE)", ex.Message)
					);

					continue;
				}

				successfulMaps++;
				results.Add(
					Localization.StringById[StringId.MapLoadedSuccessfullyText]
					.Replace("\\(MAP)", filePath)
				);

				PlayForm playForm = new(map);
				playForm.FormClosed += (_, _) => OnFormClosed();
				playForm.Show();
				openForms++;
			}

			TaskDialog.ShowDialog(new()
			{
				Caption = "PWSandbox",
				Heading = "PWSandbox",
				Icon = TaskDialogIcon.Information,

				RightToLeftLayout = Localization.AreStringsRightToLeft,
				SizeToContent = true,

				Buttons = [TaskDialogButton.OK],

				Expander = new TaskDialogExpander
				{
					CollapsedButtonText = Localization.StringById[StringId.ShowDetailsAction],
					ExpandedButtonText = Localization.StringById[StringId.HideDetailsAction],
					Text = $"""
						{Localization.StringById[StringId.DetailsSection]}
						{string.Join(Environment.NewLine + Environment.NewLine, results)}
						"""
				},

				Text = Localization.StringById[StringId.MapLoadingStatus]
					.Replace("\\(TOTAL_MAPS)", totalMaps.ToString())
					.Replace("\\(SUCCESSFUL_MAPS)", successfulMaps.ToString())
					.Replace("\\(FAILED_MAPS)", failedMaps.ToString())
			});
		}

		private void OnFormClosed()
		{
			openForms--;
			if (openForms == 0) ExitThread();
		}
	}
}
